### ISSUE TITLE
Get AudioBuffer directly

### ISSUE THREAD

**Issue by jamen** [audiojs/audio-lena#6]
```js
speaker(lena(), (err) => {
  // ...
})
```

What about some super simple usage like this?  Good for tests and examples maybe.

**Comment by dy** [comment]
@jamen sure, we can make a `audio-lena/audiobuffer` entry. Or `audio-lena/audio-buffer`? The first is  [dtype](https://github.com/shama/dtype) style, the second is valid dashcase. Hm. I think dtype style, bc other entries use dash as a type-format separator.

**Comment by jamen** [comment]
@dfcreative I don't mind `audiobuffer`.  :+1:

**Comment by jamen** [comment]
What im requesting here would be better suited for [`audio-buffer-from`](https://github.com/audiojs/audio-buffer-from) now
